### ISSUE TITLE
How can I get the best quality?

### ISSUE THREAD

**Issue by sheldygg** [krypton-byte/tiktok-downloader#19]
Hi I am using code like this
```
from tiktok_downloader import snaptik

video_url = input('enter video url: ')

a = snaptik(video_url).get_media()[0].json
print(a)
```
And every time he randomly sends a link, with full HD quality or wors.
How can I always get the best quality?

**Comment by krypton-byte** [comment]
x=sorted(snaptik(video_url).get_media(), key=lambda x:x.get_size())
hq = x[-1]

**Comment by sheldygg** [comment]
gives it away <[type: "video" watermark: False]>, I want to get a direct download link in the best quality

**Comment by sheldygg** [comment]
not work
